<img src="https://github.com/amandalemette/images/blob/08d35cced043b815b96f25c6f7d256d075079944/BiMaster/logotipo.png?raw=true"  width=1000 height=125 />

# Adição de nova linha no DataFrame

Na nossa aula, vimos como se faz a adição de nova linha no DataFrame utilizando o comando .loc(). Nas imagens a seguir, podemos ver outras duas estratégias possíveis para fazer a mesma ação. 

<center><img src="https://github.com/amandalemette/images/blob/e3e8a843c47fa1f22348750998901d992edbed3d/BiMaster/dic_append.png?raw=true"  width=700 height=400 />

<center><img src="https://github.com/amandalemette/images/blob/e97b5dc2b6638a85e6c6da4847de17499266f4e4/BiMaster/DF_append.png?raw=true"  width=800 height=400 />

O *ignore_index=True* irá ignorar o index do novo dataframe e atribuir-lhes um novo índice no dataframe original.

# Atividade 1

Dado o DataFrame a seguir, escolha uma das abordagens mostradas acima para resolver os próximos itens.

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'Nome':['Robby','Pipoca','Milho','Zulu','Arroz'],'Idade':[5,1,1,3,8],'Animal':['cachorro','papagaio','gato','cachorro','jabuti']})

In [ ]:
df

Nome  Idade    Animal
0   Robby      5  cachorro
1  Pipoca      1  papagaio
2   Milho      1      gato
3    Zulu      3  cachorro
4   Arroz      8    jabuti

- Acrescente a seguinte informação ao dataframe df:



```
[Azevedo,4,gato]
[Omar, 10, cachorro]
```



In [ ]:
info = {'Nome':['Azevedo','Omar'],'Idade':[4,10],'Animal':['gato','cachorro']}

In [ ]:
import pandas as pd

In [ ]:
IF = pd.DataFrame(info)

In [ ]:
df = df.append(IF,ignore_index = True)
df

Nome  Idade    Animal
0    Robby      5  cachorro
1   Pipoca      1  papagaio
2    Milho      1      gato
3     Zulu      3  cachorro
4    Arroz      8    jabuti
5  Azevedo      4      gato
6     Omar     10  cachorro

- Acrescente uma nova linha em df utilizando o LOC:



```
[Pituca, 12, cachorro]
```



In [ ]:
df.loc[7] = ['Pituca',12,'cachorro']

In [ ]:
df

Nome  Idade    Animal
0    Robby      5  cachorro
1   Pipoca      1  papagaio
2    Milho      1      gato
3     Zulu      3  cachorro
4    Arroz      8    jabuti
5  Azevedo      4      gato
6     Omar     10  cachorro
7   Pituca     12  cachorro

# Atividade 2

Dado o dataframe df (mesmo do exercicio anterior), responda os itens a seguir.

In [ ]:
df

Nome  Idade    Animal
0    Robby      5  cachorro
1   Pipoca      1  papagaio
2    Milho      1      gato
3     Zulu      3  cachorro
4    Arroz      8    jabuti
5  Azevedo      4      gato
6     Omar     10  cachorro
7   Pituca     12  cachorro

- Imprima a palavra papagaio de df.

In [ ]:
df.iloc[1][2]

'papagaio'

- Imprima a linha com índice 1 de df.

In [ ]:
df.iloc[1]

Nome        Pipoca
Idade            1
Animal    papagaio
Name: 1, dtype: object

- Ordene em ordem crescente por idade o dataframe df.

In [ ]:
df.sort_values('Idade')

Nome  Idade    Animal
1   Pipoca      1  papagaio
2    Milho      1      gato
3     Zulu      3  cachorro
5  Azevedo      4      gato
0    Robby      5  cachorro
4    Arroz      8    jabuti
6     Omar     10  cachorro
7   Pituca     12  cachorro

- Atualize os índices de df após a ordenação eliminando os índices antigos. 

In [ ]:
df = df.sort_values('Idade').reset_index(drop=True)
df

Nome  Idade    Animal
0   Pipoca      1  papagaio
1    Milho      1      gato
2     Zulu      3  cachorro
3  Azevedo      4      gato
4    Robby      5  cachorro
5    Arroz      8    jabuti
6     Omar     10  cachorro
7   Pituca     12  cachorro

- Troque a coluna de índices de df por:



```
[linha 0, linha 1, linha 2, ...]
```



In [ ]:
indices = ['linha 0','linha 1','linha 2', 'linha 3', 'linha 4', 'linha 5', 'linha 6', 'linha 7']

In [ ]:
df.index = indices

In [ ]:
df

Nome  Idade    Animal
linha 0   Pipoca      1  papagaio
linha 1    Milho      1      gato
linha 2     Zulu      3  cachorro
linha 3  Azevedo      4      gato
linha 4    Robby      5  cachorro
linha 5    Arroz      8    jabuti
linha 6     Omar     10  cachorro
linha 7   Pituca     12  cachorro

- Utilizando loc, imprima a palavra jabuti de df.

In [ ]:
df.loc['linha 5'][2]

'jabuti'

- Acrescente a coluna Vacinação em dia em df. Forneça as respostas para cada animal conforme sua escolha, as respostas devem ser:



1.   SIM
2.   NAO



In [ ]:
vac = ['SIM','SIM','NAO','NAO','NAO','SIM','NAO','SIM']

In [ ]:
df['Vacinação'] = vac

In [ ]:
df

Nome  Idade    Animal Vacinação
linha 0   Pipoca      1  papagaio       SIM
linha 1    Milho      1      gato       SIM
linha 2     Zulu      3  cachorro       NAO
linha 3  Azevedo      4      gato       NAO
linha 4    Robby      5  cachorro       NAO
linha 5    Arroz      8    jabuti       SIM
linha 6     Omar     10  cachorro       NAO
linha 7   Pituca     12  cachorro       SIM

- Ordene as colunas de df na seguinte ordem:



```
Nome - Vacinação em dia - Animal - Idade
```



In [ ]:
ordem = ['Nome','Vacinação','Animal','Idade']

In [ ]:
df.loc[:,ordem]

Nome Vacinação    Animal  Idade
linha 0   Pipoca       SIM  papagaio      1
linha 1    Milho       SIM      gato      1
linha 2     Zulu       NAO  cachorro      3
linha 3  Azevedo       NAO      gato      4
linha 4    Robby       NAO  cachorro      5
linha 5    Arroz       SIM    jabuti      8
linha 6     Omar       NAO  cachorro     10
linha 7   Pituca       SIM  cachorro     12

# Atividade 3

Desenvolva uma função que receba dois números como variáveis de entrada. Essa função irá retornar a informação de que o primeiro número é ou não é múltiplo do segundo número através de: 
- True 
- False


Exemplo:

```
Verifica(10,2)
>>  TRUE
```

 



In [ ]:
def multiplo(n1,n2):
  if n1%n2 == 0:
    return True
  else:
    return False

In [ ]:
multiplo(10,2)

True

In [ ]:
multiplo(3,5)

False

# Atividade 4

Em relação à função da atividade 3, modifique essa função de modo que se o número 1 for múltiplo do segundo número, a função além de retornar TRUE ela irá retornar o resultado da operação do número 1 dividido pelo número 2. 

In [ ]:
def multiplo(n1,n2):
  if n1%n2 == 0:
    return (True,n1/n2)
  else:
    return False

In [ ]:
multiplo(50,5)

(True, 10.0)

# Atividade 5

Atualize mais uma vez a função da atividade 4, acrescentando a informação de que se o número não for múltiplo, a função irá retornar FALSE e também o resultado do num1 / num2 que não será um número inteiro. 

In [ ]:
def multiplo(n1,n2):
  if n1%n2 == 0:
    return (True,n1/n2)
  else:
    return (False,n1/n2)

In [ ]:
multiplo(9,6)

(False, 1.5)

# Atividade 6

Retorne à função desenvolvida na atividade 3 e a reescreva como função anônima. 

In [ ]:
multiplo = lambda n1,n2: n1%n2 == 0 

In [ ]:
multiplo(10,2)

True

In [ ]:
multiplo(8,7)

False

# Atividade 7

Uma clínica de dermatologia está iniciando o cadastro de clientes. Nesse cadastro, as seguintes informações são salvas:

- Nome completo
- Idade
- Celular
- CPF

Desenvolva um programa que interaja com o usuário de modo a guardar essas informações automaticamente. 

In [ ]:
banco_dados = pd.DataFrame(columns = {'Nome completo','Celular','CPF','Idade'})

In [ ]:
banco_dados

Empty DataFrame
Columns: [Nome completo, Celular, CPF, Idade]
Index: []

In [ ]:
def cadastro(df):
  var0 = input('Digite o seu nome completo:')
  var1 = int(input('Digite o seu celular:'))
  var2 = int(input('Digite o seu CPF:'))
  var3 = int(input('Digite a sua idade:'))
  print('Obrigada pelas informações.')
  print('*--------*')
  df.loc[-1] = [var0,var1,var2,var3]
  df = df.reset_index(drop = True)
  return df

In [ ]:
banco_dados = cadastro(banco_dados)
banco_dados

Digite o seu nome completo:Amilton Moares
Digite o seu celular:21980349023
Digite o seu CPF:98453265423
Digite a sua idade:67
Obrigada pelas informações.
*--------*


Nome completo      Celular          CPF Idade
0    Joao Ribeiro  21984753924  98458934561    23
1  Amilton Moares  21980349023  98453265423    67

# Atividade 8

Considere a lista a seguir:



```
lista = [3,48,45,60,34,30,44]
```

Gere um dataframe com 7 colunas e 5 linhas de números inteiros aleatórios de 3 até 60 (incluindo o 60). Chame esse dataframe de df. 

Crie uma nova coluna em df de modo que ela contenha quantos números da correspondente linha pertencem à lista. Se não tiver nenhum número igual, considere 0. Chame essa nova coluna de ocorrencias. 


In [1]:
l = [3,48,45,100,146,300,444]

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame()

In [4]:
df

Empty DataFrame
Columns: []
Index: []

In [26]:
n = 5

In [27]:
df['col1'] = np.random.randint(0,444,n)
df['col2'] = np.random.randint(0,444,n)
df['col3'] = np.random.randint(0,444,n)
df['col4'] = np.random.randint(0,444,n)
df['col5'] = np.random.randint(0,444,n)
df['col6'] = np.random.randint(0,444,n)
df['col7'] = np.random.randint(0,444,n)

In [28]:
df

col1  col2  col3  col4  col5  col6  col7
0   291   193   243   418   300   337   305
1   152    22   352   168   315   126   279
2   338    13   405   327   189   333    46
3   361   145    50   402    63   354    10
4   141   423   277   242   108   214   402

In [29]:
l

[3, 48, 45, 100, 146, 300, 444]

In [30]:
df2 = df.isin(l)
df2

col1   col2   col3   col4   col5   col6   col7
0  False  False  False  False   True  False  False
1  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False
3  False  False  False  False  False  False  False
4  False  False  False  False  False  False  False

In [ ]:
resp = []
for i in df2.index:
  if df2.iloc[i].value_counts()[0] < 7:
    resp.append(df2.iloc[i].value_counts()[1])
  else:
    resp.append(0) 
  print(i)

0
1
2
3
4


In [ ]:
df['ocorrencias'] = resp 

In [ ]:
df

col1  col2  col3  col4  col5  col6  col7  ocorrencias
0   291    48    42    62   275   423   139            1
1   391   383   137   120   275   163   100            1
2   167   224   266   114   354   244    31            0
3   232    29   292   249   211    50   344            0
4    39   435    13    30    73   334    43            0

solução 2:

In [31]:
def contem(x):
  if x in l:
    return 1
  return 0

In [32]:
var = []
for i in df.columns:
  #print(i)
  var.append(df[i].apply(contem))

In [33]:
var

[0    0
 1    0
 2    0
 3    0
 4    0
 Name: col1, dtype: int64, 0    0
 1    0
 2    0
 3    0
 4    0
 Name: col2, dtype: int64, 0    0
 1    0
 2    0
 3    0
 4    0
 Name: col3, dtype: int64, 0    0
 1    0
 2    0
 3    0
 4    0
 Name: col4, dtype: int64, 0    1
 1    0
 2    0
 3    0
 4    0
 Name: col5, dtype: int64, 0    0
 1    0
 2    0
 3    0
 4    0
 Name: col6, dtype: int64, 0    0
 1    0
 2    0
 3    0
 4    0
 Name: col7, dtype: int64]

In [40]:
df2 = pd.DataFrame(var).T

In [41]:
df2

col1  col2  col3  col4  col5  col6  col7
0     0     0     0     0     1     0     0
1     0     0     0     0     0     0     0
2     0     0     0     0     0     0     0
3     0     0     0     0     0     0     0
4     0     0     0     0     0     0     0

In [44]:
df['ocorrencias'] = df2.sum(axis = 1)

In [45]:
df

col1  col2  col3  col4  col5  col6  col7  ocorrencias
0   291   193   243   418   300   337   305            1
1   152    22   352   168   315   126   279            0
2   338    13   405   327   189   333    46            0
3   361   145    50   402    63   354    10            0
4   141   423   277   242   108   214   402            0

# Atividade 9

Faça uma função que recebe dois números inteiros e retorna uma lista com os números inteiros que estão no intervalo compreendido por eles. 

In [ ]:
def intervalo(n1,n2):
  if n1==n2:
    return []
  elif n1 > n2:
    m = n2+1
    resp = []
    while m < n1:
      resp.append(m)
      m += 1
    return resp
  else:
    m = n1+1
    resp = []
    while m < n2:
      resp.append(m)
      m += 1
    return resp

In [ ]:
intervalo(2,20)

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

# Atividade 10

Alguns amigos apostaram de modo independente na mega-sena, cada aposta foi de 6 números somente. 

Desenvolva uma função que confira se o seu bilhete é o ganhador ou se acertou ao menos algum número. 

A função deve retornar quantos números foram escolhidos certo e quais números. 

Considere que a sequência sorteada foi:

In [ ]:
import numpy as np

In [ ]:
mega_sena = np.random.uniform(1,61,6)
mega_sena = mega_sena.astype(int)
mega_sena

array([50, 35, 15, 12,  6, 37])

In [ ]:
def confere(L):
  comp = np.isin(L,mega_sena)
  acertos = L[comp]
  numeros = L[comp].shape[0]
  return numeros, acertos


In [ ]:
mega_sena = np.sort(mega_sena)
mega_sena

array([ 6, 12, 15, 35, 37, 50])

In [ ]:
aposta = np.sort(np.random.uniform(1,61,6).astype(int))
aposta

array([12, 15, 32, 45, 47, 60])

In [ ]:
n,a = confere(aposta)
print(n)
print(a)

2
[12 15]
