<img src="https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Imagens/sep.png?raw=true"  width=1000 height=125 />

# Professoras

 - Amanda Lemette 
	 - prof.amanda@ica.ele.puc-rio.br
	 - [Linkedin](https://www.linkedin.com/in/amanda-lemette-brand%C3%A3o-83280918b)
   - [Youtube](https://www.youtube.com/c/AmandaLemette/featured)
   
 - Júlia Potratz
	 - prof.julia@ica.ele.puc-rio.br
	 - [Linkedin](https://www.linkedin.com/in/julia-potratz)
     
# Material 

Repositório no GitHub: [Python_BI_Master](https://github.com/jupotratz/Python_BI_Master)


# Talk 7

Esse talk será dado no dia 12/11/2021

- **Plano de aula:**
	- Vetores
         - Uso da biblioteca Numpy
         - Declaração de vetores
         - Manipulação de vetores
         - Exercícios práticos

  - Verificação de erros no código 
         - Como debuggar o código
         - Buscar auxílio de sites de suporte de Python 
      

<img src="https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Imagens/sep.png?raw=true"  width=1000 height=125 />

# Vetores

<center><img src="https://github.com/jupotratz/Python_BI_Master/blob/0a93ef10f7a528017cd3428e2c95eda1d58ad888/Turmas/2021.3/Imagens/numpy.png?raw=true"  width=800 height=190 />





Vetores em Python são declarados com a biblioteca *Numpy*. Então, para trabalharmos com eles, precisamos fazer a importação dessa biblioteca.


*   [Documentação da biblioteca Numpy](https://numpy.org)




Na importação geralmente, a biblioteca *numpy* leva a abreviação np. Mas isso é uma convenção, você pode, se quiser, colocar qualquer abreviação.

In [1]:
import numpy as np

Poderíamos fazer a importação como:

```
>   import numpy as vetores
>   import numpy as arr
>   import numpy as (serve qualquer palavra aqui)
```



<center><img src="https://github.com/jupotratz/Python_BI_Master/blob/04ead96808bf52711213e3bab75673d9c6ed042d/Turmas/2021.3/Imagens/goofy.jpg?raw=true"  width=200 height=400 />

## Declaração de vetores

In [2]:
pares = [0,2,4,6,8,10,12,14,16,18]

In [3]:
pares

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
type(pares)

list

Acabamos de criar uma lista chamada pares, mas como podemos transformá-la em vetor?


Um modo de fazer isso é usando a função da *Numpy* *array*:    

In [5]:
vet = np.array(pares)
vet

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
type(vet)

numpy.ndarray

Acabamos de criar um vetor chamado *vet* que contém números pares de 0 até 18. Na hora de criamos esse vetor, utilizamos a função *array* da biblioteca *numpy* e dentro dos ( ) incluímos uma lista chamada *pares*. 

Um segundo modo de criarmos um vetor de números inteiros pode ser usando a função da biblioteca *Numpy* *random.randint*.

In [7]:
vet1 = np.random.randint(0,20,10)

In [8]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above fo

In [9]:
vet1

array([11, 14, 12,  2,  0,  2, 16, 12,  5,  8])

Acabamos de criar um vetor chamado *vet1* de números inteiros que foi criado a partir da função random.randint. Essa função recebe como variáveis de entrada **obrigatórias**: 

- limite inferior (incluído), 
- limite superior (não incluído),
- tamanho do vetor. 

Os elementos desse vetor podem ser iguais ao limite inferior, porém não podem ser iguais ao limite superior. 

Um outro modo semelhante de criar um vetor através de números aleatórios, porém reais é:

In [ ]:
vet2 = np.random.uniform(0,20,10)
vet2

array([ 4.25125561, 10.45866124,  8.44838956,  4.21137568,  8.61315796,
        7.95264077,  7.67482626, 14.34767664, 19.19422351,  4.93756319])

A função *random.uniform* funciona de modo bem similar à função *random.randint*, porém a *random.uniform* gera números reais. Ambas as funções geram números aleatórios que seguem a distribuição uniforme, ou seja, cada valor dentro do intervalo especificado tem a mesma probabilidade de ser sorteado. 

Para mais informações a respeito da geração de números aleatórios, que seguem outros tipos de distribuições, utilizando *numpy*, assista o vídeo:

[Distribuições de Probabilidades](https://youtu.be/ld_CP_0H46k)

**Bom, já vimos aqui 2 formas de criarmos um vetor, você conhece mais alguma?**

Algumas dicas para responder essa pergunta, conseguimos criar vetores

*   A partir de Dataframes
*   Usando a função [linspace](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html) 
*   A partir de outras distribuições de probabilidades da Numpy: [random.exponential](https://numpy.org/doc/stable/reference/random/generated/numpy.random.exponential.html), [random.binomial](https://numpy.org/doc/stable/reference/random/generated/numpy.random.binomial.html)
*   Usando [numpy.arange](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)







vamos testar esses outros modos?

### Declaração de vetores de mais de uma dimensão

Até o presente momento, somente vimos como se faz a declaração de vetores 1-D, mas para criar matrizes, ou, vetores multidimensionais, o procedimento é análogo. Vamos testar com alguns exemplos. 

- Crie uma matriz de números aleatórios inteiros de 0 a 100 com 5 colunas e 7 linhas. 

In [13]:
np.random.seed(100)
vet = np.random.randint(low=0, \
                        high=100, \
                        size=(7,5))
vet

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98],
       [53, 66, 98, 14, 34],
       [24, 15, 60, 58, 16],
       [ 9, 93, 86,  2, 27],
       [ 4, 31,  1, 13, 83],
       [ 4, 91, 59, 67,  7]])

Repare no código acima, a função *randint* pediu como argumentos:
- O limite inferior (*low*) 0
- O limite superior (*high*) 100
- A dimensão da matriz (*size* = número de linhas, número de colunas)

Um outro modo de criarmos vetores multidimensionais é fornecendo diretamente os elementos do conjunto. 

In [8]:
vet1 = np.array([[1,2],[4,3],[5,6],[9,8]])
vet1

array([[1, 2],
       [4, 3],
       [5, 6],
       [9, 8]])

Criamos a matriz *vet1* que possui duas colunas e 4 linhas. 

- Crie uma matriz de números aleatórios inteiros de 0 a 100 com 10 colunas e 3 linhas.

<img src="https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Imagens/sep.png?raw=true"  width=1000 height=125 />

## Atributos de Numpy Arrays

In [9]:
np.random.seed(100)
arr = np.random.randint(0,100,(5,4))
arr

array([[ 8, 24, 67, 87],
       [79, 48, 10, 94],
       [52, 98, 53, 66],
       [98, 14, 34, 24],
       [15, 60, 58, 16]])

Dada a variável *arr*, vamos entender alguns atributos importantes do objeto *ndarray*.

### ndarray.ndim

*ndarray.ndim* retorna quantas dimensões tem o vetor.

### ndarray.shape

*ndarray.shape* retorna as dimensões do vetor (número de linhas e número de colunas caso o vetor seja 2-D).

### ndarray.size

*ndarray.size* retorna o número total de elementos do array. 

### ndarray.dtype

*ndarray.dtype* retorna o tipo dos elementos armazenados no array.

<img src="https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Imagens/sep.png?raw=true"  width=1000 height=125 />

## Funções aplicadas a vetores

Existem funções prontas para:

- somatório: **np.sum( )**
- média: **np.mean( )**
- desvio padrão: **np.std( )**
- variância: **np.var( )**

Exercício: Aplique as 4 funções mostradas acima no vetor vet:

In [ ]:
np.random.seed(100)

In [ ]:
vet = np.random.uniform(0,20,size=40)

In [ ]:
vet 

array([10.86809884,  5.5673877 ,  8.49035181, 16.89552265,  0.09437712,
        2.43138242, 13.41498169, 16.5170551 ,  2.73413179, 11.50186659,
       17.82643909,  4.18404244,  3.70656439,  2.16753781,  4.39394985,
       19.57247569, 16.23366298,  3.43882025, 16.32449497,  5.48147494,
        8.63408367, 18.80059639, 16.35298758,  6.722239  ,  3.50820907,
        7.45664093,  0.11377015,  5.04852707, 15.91325017,  0.30509942,
       11.97686754, 12.07609078,  2.10295371,  7.6388689 ,  0.72952113,
       17.80823127, 19.61841714,  1.19883978, 17.81091889, 11.53802999])

<img src="https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Imagens/sep.png?raw=true"  width=1000 height=125 />

## Manipulação de vetores

### Eliminação de elementos em vetores

In [ ]:
np.random.seed(1000)

In [ ]:
vet = np.random.randint(0,2000,size=40)
vet

array([ 199,  146,  256,  740, 1885, 1838,  596, 1233,  726, 1893, 1853,
        542, 1837, 1921, 1044,  241,  743,  420, 1493,  944,  502,  802,
        473, 1822, 1215, 1943, 1248,  332, 1547, 1258, 1032, 1019,  160,
        821, 1043, 1440,  916, 1827,  739, 1707])

Considerando o vetor *vet* acima, se quiséssemos remover todos os números múltiplos de 3, como faríamos?





1. Bom, primeiro precisamos saber como identificar os números múltiplos de 3. 

2. Em seguida, precisamos saber como eliminar elementos dentro de um vetor. 

3. Por último, precisamos imprimir o vetor resultante. 

Vamos, agora, passar por cada uma dessas etapas: 

**Identificação de números múltiplos de 3**

---


**Eliminação de elementos em um vetor**

---

O modo de eliminarmos elemento em um vetor é pelo uso da: 

*   [função *delete*](https://numpy.org/doc/stable/reference/generated/numpy.delete.html)



**Impressão do vetor**

---

### Adição de elementos em vetores

Como conseguimos adicionar elementos a vetores já declarados? 



**Você tem alguma ideia?**

Podemos usar duas funções com nomes já conhecidos por você:

*   [função *append*](https://numpy.org/doc/stable/reference/generated/numpy.append.html)
*   [função *insert*](https://numpy.org/doc/stable/reference/generated/numpy.insert.html)



In [ ]:
np.random.seed(50)

In [ ]:
arr = np.random.uniform(5,1000,8)
arr

array([497.12863731, 231.94268893, 259.19655414, 399.34826017,
       380.4285222 , 996.591359  , 411.15621433, 773.03452487])

Vamos adicionar o número 35.4 na última posição de *arr*.

Agora, vamos adicionar o número 10.2 na terceira posição de *arr*.

Por fim, vamos adicionar os números 23.4 e 36.7 nas posições 5 e 6 respectivamente, porém faça essa adição por meio de uma única operação. 

### Selecionando e modificando partes de um vetor

In [ ]:
np.random.seed(50)
arr = np.random.randint(-10,10,10)
arr 

array([  6, -10,   1,   3,  -9,  -6,  -4,  -5,  -4,   3])

Selecione apenas do quarto elemento de *arr* até o nono elemento.

Selecione do quinto elemento ao último. 

Selecione do primeiro elemento ao sexto em *arr*.

Ainda usando o mesmo vetor *arr*, o transforme em uma matrix de 2 colunas e 5 linhas. 

Para ajudar na resolução dessa atividade, vamos checar antes a dimensão atual de *arr*.

In [ ]:
np.random.seed(50)
arr = np.random.randint(-10,10,10)
arr

array([  6, -10,   1,   3,  -9,  -6,  -4,  -5,  -4,   3])

In [ ]:
arr.shape

(10,)

Como podemos ver, *arr* possui 10 linhas e não tem uma segunda dimensão definida. 

Para transformarmos nosso vetor 1-D em 2-D, vamos fazer uso da [função *reshape*](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html).

Lendo a documentação de *reshape* será que agora conseguimos resolver o exercício?

### Indexação booleana

Esta indexação possui alguma expressão booleana como índice. Esses elementos são retornados quando satisfazem essa expressão booleana. É usado para filtrar os valores de elemento desejados.

 - Podem ser utilizados em um vetor ou com multiplos vetores.

In [15]:
# Criando um array com nomes
nomes = np.array(['Júlia', 'Amanda','Manoela','Júlia','Evylen','Melissa','Bruna'])
nomes

array(['Júlia', 'Amanda', 'Manoela', 'Júlia', 'Evylen', 'Melissa',
       'Bruna'], dtype='<U7')

In [14]:
# Criando um array n dimensional (com numero de linhas igual a quantidade de nomes do meu array de nomes)
array = np.random.randn(7,5)
array

array([[-0.53128038,  1.02973269, -0.43813562, -1.11831825,  1.61898166],
       [ 1.54160517, -0.25187914, -0.84243574,  0.18451869,  0.9370822 ],
       [ 0.73100034,  1.36155613, -0.32623806,  0.05567601,  0.22239961],
       [-1.443217  , -0.75635231,  0.81645401,  0.75044476, -0.45594693],
       [ 1.18962227, -1.69061683, -1.35639905, -1.23243451, -0.54443916],
       [-0.66817174,  0.00731456, -0.61293874,  1.29974807, -1.73309562],
       [-0.9833101 ,  0.35750775, -1.6135785 ,  1.47071387, -1.1880176 ]])

**Obs:** Vamos supor que cada linha do nosso array criado corresponde a um nome e que desejamos selecionar todas as linhas com o nome Júlia

- Podemos comparar o array de nome com uma string

In [17]:
nomes == 'Júlia'

array([ True, False, False,  True, False, False, False])

**Obs:** Podemos passar esse array booleano com elemento de indexação, onde o resultado serão os elementos verdadeiros (True)

In [18]:
array[nomes == 'Júlia']

array([[-0.53128038,  1.02973269, -0.43813562, -1.11831825,  1.61898166],
       [-1.443217  , -0.75635231,  0.81645401,  0.75044476, -0.45594693]])

O array booleano deve ser do mesmo tamanho do eixo do array que está sendo indexado. 

    - No nosso caso o array booleano tinha 7 elementos e o nosso array a ser indexado possuia 7 elementos no eixo 0

#### Vamos praticar?


1. Crie um vetor unidimensional com 100 elementos contendo números inteiros aleatórios de 0 a 100 e selecione, separadamente, as seguintes informações:

    - Todos os elementos pares
    - Todos os elementos impares
    - Todos os elementos no intervalo de 10 a 20
    - Todo os elementos menores que 15 ou maiores que 80

In [38]:
array = np.random.randint(0,100,size=(100,))
array

array([ 3, 28, 35, 31, 19, 52, 41, 78, 50, 46, 71, 49, 50, 77, 58, 76, 99,
        2, 61, 60, 18, 35,  2, 55, 96, 63, 70, 25, 95, 56, 58, 82, 76, 60,
       17, 33, 66, 94, 18, 66, 36,  7, 62,  1, 85, 77, 57, 30, 92, 16, 81,
       96, 20, 35, 82, 23, 42, 99,  7, 77, 47, 18, 43, 87, 92, 88, 85,  1,
       94, 92, 91, 41, 22, 77, 48, 89, 59,  9, 69, 50, 62, 42, 71, 49, 14,
       90,  1,  7, 63, 47, 57, 26, 82, 16, 51, 87, 10, 68, 39, 98])

- Todos os elementos pares

In [39]:
array[array%2==0]

array([28, 52, 78, 50, 46, 50, 58, 76,  2, 60, 18,  2, 96, 70, 56, 58, 82,
       76, 60, 66, 94, 18, 66, 36, 62, 30, 92, 16, 96, 20, 82, 42, 18, 92,
       88, 94, 92, 22, 48, 50, 62, 42, 14, 90, 26, 82, 16, 10, 68, 98])

- Todos os elementos ímpares

In [40]:
array[array%2==1]

array([ 3, 35, 31, 19, 41, 71, 49, 77, 99, 61, 35, 55, 63, 25, 95, 17, 33,
        7,  1, 85, 77, 57, 81, 35, 23, 99,  7, 77, 47, 43, 87, 85,  1, 91,
       41, 77, 89, 59,  9, 69, 71, 49,  1,  7, 63, 47, 57, 51, 87, 39])

- Todos os elementos no intervalo de 10 a 20

Quando temos multiplas condições podemos utilizar a função <code>np.where()</code>

In [45]:
array[(array >= 10) & (array <= 20)]

array([19, 18, 17, 18, 16, 20, 18, 14, 16, 10])

O símbolo <code>&</code> nesse caso faz o papel do <code>and</code>. 

- Todo os elementos menores que 15 ou maiores que 80

In [47]:
array[(array < 10) | (array > 80)]

array([ 3, 99,  2,  2, 96, 95, 82, 94,  7,  1, 85, 92, 81, 96, 82, 99,  7,
       87, 92, 88, 85,  1, 94, 92, 91, 89,  9, 90,  1,  7, 82, 87, 98])

O símbolo <code>|</code> nesse caso faz o papel do <code>or</code>. 

### Concatenação de vetores

A concatenação de vetores é feita pelo uso da função *numpy.concatenate*. 

In [25]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [26]:
x

array([1, 2, 3])

In [27]:
y

array([3, 2, 1])

In [29]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

E se em vez de vetores 1-D, tivéssemos vetores 2-D, como a concatenação é feita?

#### np.vstack & np.hstack

Quando temos vetores de dimensões diferentes, para juntá-los podemos fazer uso das funções:      
- np.vstack
- np.hstack

In [34]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [35]:
arr2 = np.array([[9, 8, 7,6],[6, 5, 4,3]])
arr2

array([[9, 8, 7, 6],
       [6, 5, 4, 3]])

In [36]:
np.vstack([arr1,arr2])

array([[1, 2, 3, 4],
       [9, 8, 7, 6],
       [6, 5, 4, 3]])

Para que *vstack* funcione, ambos os vetores precisam ter o mesmo número de colunas. 

In [39]:
arr3 = np.array([40,50])
arr3

array([40, 50])

In [40]:
np.hstack([arr1,arr3])

array([ 1,  2,  3,  4, 40, 50])

Para que *hstack* funcione, ambos os vetores precisam ter o mesmo número de linhas. 

### Quebra de arrays

Para particionar vetores, podemos usar a função *numpy.split*, vamos testá-la:

In [42]:
arr = np.array([1, 2, 3, 99, 99, 3, 2, 1])
arr

array([ 1,  2,  3, 99, 99,  3,  2,  1])

Vamos partir esse vetor a partir da posição 2: 

In [43]:
np.split(arr,[2])

[array([1, 2]), array([ 3, 99, 99,  3,  2,  1])]

e se quisermos criar 4 pedaços do vetor, basta dizermos em quais posições queremos que essas partições sejam feitas. Por exemplo, vamos quebrar o vetor nas posições 2,5 e 7

In [45]:
arr

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [44]:
np.split(arr,[2,5,7])

[array([1, 2]), array([ 3, 99, 99]), array([3, 2]), array([1])]

In [46]:
x,y,w,z = np.split(arr,[2,5,7])
print(x)
print(y)
print(w)
print(z)

[1 2]
[ 3 99 99]
[3 2]
[1]


Na quebra do vetor, podemos fazer uso também das funções:    
- vsplit
- hsplit

<img src="https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Imagens/sep.png?raw=true"  width=1000 height=125 />

## Salvamento de dados

#### Montagem do drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!ls 'drive/MyDrive/Colab Notebooks'

In [ ]:
# Importar a biblioteca os
import os

# Utilizando a função .chdir()
os.chdir('drive/MyDrive/Colab Notebooks')

In [ ]:
!ls

- O Numpy é capaz de salvar e carregar aqrquivos de a para o disco, seja em formato texto ou formato binário. Para tal são utilizadas as seguintes funções:

    - **np.save(** path **)** : para salvar o arquivo no diretório (path) especificado
    - **np.load(** path **)** : faz o download do arquivo cujo diretório (path) é o especificado


- Criando arrays

In [ ]:
array1 = np.reshape(np.arange(16),newshape=(4,4))
array2 = np.full(shape=(3,3),fill_value=3)
array3 = np.array([[1,2],[2,4]])

- Salvando o array1 no diretório corrente

In [ ]:
np.save('array1',array1)

- Salvando o array2 no diretório corrente

In [ ]:
np.save('array2.npy',array2)

Rearem que no salvamento do array1 nós não colocamos a estensão. Mas por default a estensão sempre será <code>.npy</code>

- Para fazer o download de uma arquivo numpy basta usar a função <code>.load()</code> da biblioteca numpy.

In [ ]:
# fazendo o download de arquivos numpy (*.npy)
array = np.load('array1.npy')

<img src="https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Imagens/sep.png?raw=true"  width=1000 height=125 />

## Broadcasting

Em muitos casos, é necessário trabalhar com arrays com um número distinto de elementos, ou de formas diferentes. Nesse caso, é necessário entender as regras do NumPy que difundem as informações do array menor para o array maior.

O termo difusão (broadcasting) descreve como NumPy trata arrays de dimensões diferentes em operações aritméticas. O array menor é “difundido” a uma array maior para que tenham as mesmas dimensões. 

Vamos ver um exemplo prático

<img src='https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Broadcasting.png?raw=true' align="center" />

- **Exemplo 1**

In [52]:
arr1 = np.ones((4,2),dtype='int')
arr1

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [53]:
arr2 = np.array([2,3])

In [54]:
arr1 + arr2

array([[3, 4],
       [3, 4],
       [3, 4],
       [3, 4]])

In [55]:
arr1 * arr2

array([[2, 3],
       [2, 3],
       [2, 3],
       [2, 3]])

- **Exemplo 1**

In [56]:
arr1 = np.array([[2], [3], [4]])
arr1

array([[2],
       [3],
       [4]])

In [57]:
arr2 = np.array([2, 3, 4])
arr2

array([2, 3, 4])

In [58]:
arr1 + arr2

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [59]:
arr1 * arr2

array([[ 4,  6,  8],
       [ 6,  9, 12],
       [ 8, 12, 16]])

### Exercício - Broadcasting

Faça um programa que gere o resultado esperado conforme a imagem abaixo:

- Dicas:
    - Crie arrays como especificado na imagem, utilize para isso os conhecimentos adquiridos nas aulas
    - Lembre que as operações de array de tamanhos distintos podem gerar  resultados inesperados (a medida que for desenvolvendo o seu programa teste-o)

<img src='https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Broadcasting_exerc%C3%ADcio.png?raw=true' height="800" width="650" align="center" />
