<img src="https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Imagens/sep.png?raw=true"  width=1000 height=125 />

# Professoras

 - Amanda Lemette 
	 - prof.amanda@ica.ele.puc-rio.br
	 - [Linkedin](https://www.linkedin.com/in/amanda-lemette-brand%C3%A3o-83280918b)
   - [Youtube](https://www.youtube.com/c/AmandaLemette/featured)
   
 - Júlia Potratz
	 - prof.julia@ica.ele.puc-rio.br
	 - [Linkedin](https://www.linkedin.com/in/julia-potratz)
     
# Material 

Repositório no GitHub: [Python_BI_Master](https://github.com/jupotratz/Python_BI_Master)


# Talk 7

- **Plano de aula:**
	- Vetores
         - uso da biblioteca Numpy
         - declaração de vetores
         - manipulação de vetores
         - exercícios práticos

  - verificação de erros no código 
         - como debuggar o código
         - buscar auxílio de sites de suporte de Python 
      

<img src="https://github.com/jupotratz/Python_BI_Master/blob/main/Turmas/2021.3/Imagens/sep.png?raw=true"  width=1000 height=125 />

# Vetores

<center><img src="https://github.com/jupotratz/Python_BI_Master/blob/0a93ef10f7a528017cd3428e2c95eda1d58ad888/Turmas/2021.3/Imagens/numpy.png?raw=true"  width=800 height=190 />





Vetores em Python são declarados com a biblioteca *Numpy*. Então, para trabalharmos com eles, precisamos fazer a importação dessa biblioteca.


*   [Site da biblioteca Numpy](https://numpy.org)




Diferente das listas, os vetores só são capazes de armazenar números e do mesmo tipo. Você nunca terá um vetor com elementos inteiros e reais. Todos os elementos do vetor serão inteiros ou todos serão reais.

Geralmente, a biblioteca *numpy* leva a abreviação np. Mas isso é uma convenção, você pode, se quiser, colocar qualquer abreviação.

In [1]:
import numpy as np

Poderíamos fazer a importação como:

```
>   import numpy as vetores
>   import numpy as arr
>   import numpy as (serve qualquer palavra aqui)
```



<center><img src="https://github.com/jupotratz/Python_BI_Master/blob/04ead96808bf52711213e3bab75673d9c6ed042d/Turmas/2021.3/Imagens/goofy.jpg?raw=true"  width=200 height=400 />

## Declaração de vetores

In [2]:
pares = [0,2,4,6,8,10,12,14,16,18]

In [3]:
pares

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
type(pares)

list

Acabamos de criar uma lista chamada pares, mas como podemos transformá-la em vetor?


Um modo de fazer isso é usando a função da *Numpy* *array*:    

In [5]:
vet = np.array(pares)
vet

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
type(vet)

numpy.ndarray

Acabamos de criar um vetor chamado *vet* que contém números pares de 0 até 18. Na hora de criamos esse vetor, utilizamos a função *array* da biblioteca *numpy* e dentro dos ( ) incluímos uma lista chamada *pares*. 

Um segundo modo de criarmos um vetor de números inteiros pode ser usando a função da biblioteca *Numpy* *random.randint*.

In [9]:
vet1 = np.random.randint(0,20,10)

In [10]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [11]:
vet1

array([ 1,  0, 13,  7,  4, 14, 11,  0, 17,  6])

Acabamos de criar um vetor chamado *vet1* de números inteiros que foi criado a partir da função random.randint. Essa função recebe como variáveis de entrada **obrigatórias**: 

- limite inferior (incluído), 
- limite superior (não incluído),
- tamanho do vetor. 

Os elementos desse vetor podem ser iguais ao limite inferior, porém não podem ser iguais ao limite superior. 

Um outro modo semelhante de criar um vetor através de números aleatórios, porém reais é:

In [12]:
vet2 = np.random.uniform(0,20,10)
vet2

array([ 4.25125561, 10.45866124,  8.44838956,  4.21137568,  8.61315796,
        7.95264077,  7.67482626, 14.34767664, 19.19422351,  4.93756319])

A função *random.uniform* funciona de modo bem similar à função *random.randint*, porém a *random.uniform* gera números reais. Ambas as funções geram números aleatórios que seguem a distribuição uniforme, ou seja, cada valor dentro do intervalo especificado tem a mesma probabilidade de ser sorteado. 

Para mais informações a respeito da geração de números aleatórios, que seguem outros tipos de distribuições, utilizando *numpy*, assista o vídeo:

[Distribuições de Probabilidades](https://youtu.be/ld_CP_0H46k)

**Bom, já vimos aqui 2 formas de criarmos um vetor, você conhece mais alguma?**

Algumas dicas para responder essa pergunta, conseguimos criar vetores

*   a partir de Dataframes
*   usando a função *linspace* 
*   
*   







vamos testar esses outros modos?

## Funções aplicadas a vetores

Existem funções prontas para:

- somatório: **np.sum( )**
- média: **np.mean( )**
- desvio padrão: **np.std( )**
- variância: **np.var( )**

Exercício: Aplique as 4 funções mostradas acima no vetor vet:

In [21]:
np.random.seed(100)

In [22]:
vet = np.random.uniform(0,20,size=40)

In [23]:
vet 

array([10.86809884,  5.5673877 ,  8.49035181, 16.89552265,  0.09437712,
        2.43138242, 13.41498169, 16.5170551 ,  2.73413179, 11.50186659,
       17.82643909,  4.18404244,  3.70656439,  2.16753781,  4.39394985,
       19.57247569, 16.23366298,  3.43882025, 16.32449497,  5.48147494,
        8.63408367, 18.80059639, 16.35298758,  6.722239  ,  3.50820907,
        7.45664093,  0.11377015,  5.04852707, 15.91325017,  0.30509942,
       11.97686754, 12.07609078,  2.10295371,  7.6388689 ,  0.72952113,
       17.80823127, 19.61841714,  1.19883978, 17.81091889, 11.53802999])

## Manipulação de vetores

### Eliminação de elementos em vetores

In [24]:
np.random.seed(1000)

In [27]:
vet = np.random.randint(0,2000,size=40)
vet

array([ 199,  146,  256,  740, 1885, 1838,  596, 1233,  726, 1893, 1853,
        542, 1837, 1921, 1044,  241,  743,  420, 1493,  944,  502,  802,
        473, 1822, 1215, 1943, 1248,  332, 1547, 1258, 1032, 1019,  160,
        821, 1043, 1440,  916, 1827,  739, 1707])

Considerando o vetor *vet* acima, se quiséssemos remover todos os números múltiplos de 3, como faríamos?





1. Bom, primeiro precisamos saber como identificar os números múltiplos de 3. 

2. Em seguida, precisamos saber como eliminar elementos dentro de um vetor. 

3. Por último, precisamos imprimir o vetor resultante. 

Vamos, agora, passar por cada uma dessas etapas: 

**Identificação de números múltiplos de 3**

---


**Eliminação de elementos em um vetor**

---

O modo de eliminarmos elemento em um vetor é pelo uso da: 

*   [função *delete*](https://numpy.org/doc/stable/reference/generated/numpy.delete.html)



**Impressão do vetor**

---

### Adição de elementos em vetores

Como conseguimos adicionar elementos a vetores já declarados? 



**Você tem alguma ideia?**

Podemos usar duas funções com nomes já conhecidos por você:

*   [função *append*](https://numpy.org/doc/stable/reference/generated/numpy.append.html)
*   [função *insert*](https://numpy.org/doc/stable/reference/generated/numpy.insert.html)



In [28]:
np.random.seed(50)

In [29]:
arr = np.random.uniform(5,1000,8)
arr

array([497.12863731, 231.94268893, 259.19655414, 399.34826017,
       380.4285222 , 996.591359  , 411.15621433, 773.03452487])

Vamos adicionar o número 35.4 na última posição de *arr*.

Agora, vamos adicionar o número 10.2 na terceira posição de *arr*.

Por fim, vamos adicionar os números 23.4 e 36.7 nas posições 5 e 6 respectivamente, porém faça essa adição por meio de uma única operação. 

### Selecionando e modificando partes de um vetor

In [40]:
np.random.seed(50)
arr = np.random.randint(-10,10,10)
arr 

array([  6, -10,   1,   3,  -9,  -6,  -4,  -5,  -4,   3])

Selecione apenas do quarto elemento de *arr* até o nono elemento.

Selecione do quinto elemento ao último. 

Selecione do primeiro elemento ao sexto em *arr*.

Ainda usando o mesmo vetor *arr*, o transforme em uma matrix de 2 colunas e 5 linhas. 

Para ajudar na resolução dessa atividade, vamos checar antes a dimensão atual de *arr*.

In [41]:
np.random.seed(50)
arr = np.random.randint(-10,10,10)
arr

array([  6, -10,   1,   3,  -9,  -6,  -4,  -5,  -4,   3])

In [42]:
arr.shape

(10,)

Como podemos ver, *arr* possui 10 linhas e não tem uma segunda dimensão definida. 

Para transformarmos nosso vetor 1-D em 2-D, vamos fazer uso da [função *reshape*](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html).

Lendo a documentação de *reshape* será que agora conseguimos resolver o exercício?